### ISSUE TITLE
HCL Action syntax will be deprecated on September 30

### ISSUE THREAD

**Issue by Kesin11** [yuichielectric/danger-textlint-actions#2]
Hi, thank you for creating cool actions.
I'm using it for checking my blog text before post.

I'm trying new yaml syntax based github actions and I found announcement that old HCL Action syntax will be deprecated on September 30.

https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax

> GitHub Actions now uses YAML syntax in workflow files. Support for the HCL syntax in GitHub Actions will be deprecated on September 30, 2019. To continue using workflows that you created with the HCL syntax, you'll need to migrate the workflow files to the new YAML syntax using the migration script.

Do you have any plan to migrate this actions to new yaml syntax?

**Comment by yuichielectric** [comment]
Hi 👋  @Kesin11, thanks you for reaching out to me. Sorry for my late response 🙇 

Through HCL based workflow files are no longer supported, Docker based action is still supported for the current GitHub Actions.

https://help.github.com/en/articles/creating-a-docker-container-action

But, it seems I need to modify some tiny things like [this](https://help.github.com/en/articles/creating-a-docker-container-action#create-an-action-metadata-file) and updating README, I'll look into it this week.

**Comment by yuichielectric** [comment]
@Kesin11 I've released 1.1.0 https://github.com/yuichielectric/danger-textlint-actions/releases/tag/1.1.0
The previous version still works fine on the current GitHub Actions, and no feature is added. I just updated tiny things here #3 

I'm closing this issue, but if you have anything to add, feel free to reopen this issue 👍

**Comment by Kesin11** [comment]
Thank you for support new github actions!
It works properly in my actions 😄

**Comment by yuichielectric** [comment]
Happy to hear that @Kesin11 ! 🎉
